name: release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release (e.g. @tofrankie/action@0.0.1)
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-dist-branch:
    runs-on: ubuntu-latest
    env:
      RELEASE_GIT_USER_NAME: github-actions[bot]
      RELEASE_GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      TOFRANKIE_SCOPE_NPM_TOKEN: ${{ secrets.TOFRANKIE_SCOPE_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        id: checkout
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build action
        run: pnpm run action:build
      - name: Create GitHub Release
        run: pnpm run npm:build && node bin/cli.js --yes --tag "${{ github.event.inputs.tag || github.ref_name }}" --ref "${{ steps.checkout.outputs.commit }}" --token "${{ github.token }}"
      - name: Publish dist branch
        run: pnpm run action:release
